import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { resolve } from 'node:path';
export default defineConfig({
    plugins: [
        react(),
        VitePWA({
            registerType: 'autoUpdate',
            includeAssets: ['favicon.svg', 'icon-192.png', 'icon-512.png'],
            manifest: {
                name: 'OmniTab — Guitar Companion',
                short_name: 'OmniTab',
                description: 'Tablature viewer, tuner, amp sim and AI transcription — 100% client-side, offline capable.',
                theme_color: '#0a0a0a',
                background_color: '#0a0a0a',
                display: 'standalone',
                orientation: 'any',
                start_url: '/',
                // Icons: SVG for crispness on desktop/iOS, PNG for Android's
                // "install as app" menu (where SVG support is inconsistent).
                // PNGs are generated by `scripts/generate-icons.mjs` — run
                // `npm run gen:icons` after changing the design.
                icons: [
                    {
                        src: 'icon-192.png',
                        sizes: '192x192',
                        type: 'image/png',
                        purpose: 'any',
                    },
                    {
                        src: 'icon-512.png',
                        sizes: '512x512',
                        type: 'image/png',
                        purpose: 'any',
                    },
                    {
                        src: 'icon-512.png',
                        sizes: '512x512',
                        type: 'image/png',
                        purpose: 'maskable',
                    },
                    {
                        src: 'favicon.svg',
                        sizes: 'any',
                        type: 'image/svg+xml',
                        purpose: 'any',
                    },
                ],
            },
            workbox: {
                // AlphaTab ships hefty font/soundfont payloads — let Workbox precache them
                // so the app boots offline after the first visit.
                globPatterns: ['**/*.{js,css,html,svg,png,woff2,sf2,bravura}'],
                maximumFileSizeToCacheInBytes: 10 * 1024 * 1024, // 10 MB (soundfont is ~6 MB)
                runtimeCaching: [
                    {
                        // Cache AlphaTab CDN assets so the viewer works fully offline after first load.
                        urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/npm\/@coderline\/alphatab/,
                        handler: 'CacheFirst',
                        options: {
                            cacheName: 'alphatab-cdn',
                            expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 30 },
                        },
                    },
                    {
                        // Cache the basic-pitch TF.js model once.
                        urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/npm\/@spotify\/basic-pitch/,
                        handler: 'CacheFirst',
                        options: {
                            cacheName: 'basic-pitch-model',
                            expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 90 },
                        },
                    },
                ],
            },
        }),
    ],
    resolve: {
        alias: {
            '@': resolve(__dirname, './src'),
        },
    },
    server: {
        port: 5173,
        host: true, // expose on LAN so you can test from your Samsung A52s
    },
    build: {
        target: 'es2022',
        sourcemap: true,
        // AlphaTab is 1.2 MB minified and lives in its own lazy-loaded chunk.
        // Raise the threshold so we only hear about chunks that genuinely grew
        // — not the known big-lib one we already split out.
        chunkSizeWarningLimit: 1500,
        rollupOptions: {
            output: {
                // Split heavy libs into their own chunks so the initial HTML payload
                // stays tiny. basic-pitch is NOT listed here: it lives exclusively
                // inside the Web Worker chunk now, so Rollup handles its splitting.
                manualChunks: {
                    alphatab: ['@coderline/alphatab'],
                    tonal: ['tonal'],
                },
            },
        },
    },
    // The basic-pitch worker uses `await import()` for code-splitting; the
    // default IIFE worker format rejects that. ES module workers are supported
    // in every browser OmniTab targets (Chrome 80+, Firefox 114+, Safari 15+).
    worker: {
        format: 'es',
    },
    optimizeDeps: {
        exclude: ['@coderline/alphatab'],
    },
});
